Test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -230,7 +230,7 @@ jobs:
             tar xf 2019-Aug-Ubuntu.tar.xz
 
       - run:
-          name: Run clang-tidy
+          name: Build Vapor
           command: |
             git clone https://github.com/NCAR/VAPOR.git /root/VAPOR
             cd /root/VAPOR
@@ -243,7 +243,26 @@ jobs:
             -DBUILD_TEST_APPS=ON \
             -DUSE_OMP=ON
             make -j4
-            git diff $(git merge-base --fork-point origin/main HEAD) HEAD | \
+
+      - run:
+          name: Run clang-tidy
+          command: |
+            cd /root/VAPOR
+            mergeBase=$(git merge-base --fork-point origin/main HEAD)
+            if [ -z "$mergeBase" ]
+            then
+                mergeBase=$(git merge-base origin/main HEAD)
+                if [ -z "$mergeBase" ]
+                then
+                    echo "Cannot find common ancestor for origin/main and HEAD"
+                    exit 1
+                else
+                    echo "Merge-base found with --fork-point at $mergeBase"
+                fi
+            else
+                echo "Merge-base found with at $mergeBase"
+            fi
+            git diff $mergeBase HEAD | \
             /usr/bin/clang-tidy-diff-14.py -path /root/VAPOR -p1 -checks=cppcoreguidelines* 2>&1    | \
             tee /tmp/clangTidyOutput.txt
 
